# Generated by Django 3.1.7 on 2021-04-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='p_deliver',
            field=models.CharField(choices=[('Cart', 'Cart'), ('Ordered', 'Ordered'), ('Received', 'Received')], max_length=200),
        ),
    ]
